language: r
cache: packages
warnings_are_errors: true

# Test on multiple dists with every flavor of R
matrix:
  include:
    - &trusty
      os: linux
      dist: trusty
      r: oldrel
      addons:
        apt:
          sources:
            # PPA is only needed for (legacy) Trusty. Can be removed when Trusty is EOL.
            - sourceline: 'ppa:chris-lea/libsodium'
          packages:
            - libsodium-dev
    - <<: *trusty
      r: release
    - <<: *trusty
      r: devel

    - &xenial
      os: linux
      dist: xenial
      r: oldrel
      addons:
        apt:
          packages:
            - libsodium-dev
    - <<: *xenial
      r: release
      r_packages:
        - covr
      after_success:
        # testing coverage
        - Rscript -e 'library(covr);codecov()'
    - <<: *xenial
      r: devel

    - &osx
      os: osx
      brew_packages: libsodium
      r: oldrel
    - <<: *osx
      r: release
    - <<: *osx
      r: devel
