language: r
cache: packages
warnings_are_errors: true

# test on all flavors of R
r:
  - oldrel
  - release
  - devel

# Test on multiple dists
os:
  - linux
  - osx
dist:
  - trusty
  - xenial
brew_packages: libsodium
# matrix:
#   include:
#     - os: linux
#       dist: trusty
#     - os: linux
#       dist: xenial
#     - os: osx
#       brew_packages: libsodium

# PPA is only needed for (legacy) Trusty. Can be removed when Trusty is EOL.
addons:
  apt:
    sources:
      - sourceline: 'ppa:chris-lea/libsodium'
    packages:
      - libsodium-dev

jobs:
  include:
    - stage: "post processing"
      name: "covr"
      r: release
      dist: xenial
      r_packages:
        - covr
      # testing coverage
      after_success:
        - Rscript -e 'library(covr);codecov()'
