language: r
sudo: required
r_binary_packages:
  - testthat
  - xml
  - base64enc
  - rmarkdown
  - stringi
  - jsonlite
  - httpuv
  - htmlwidgets
r_github_packages:
  - jimhester/covr
  - datastorm-open/visNetwork
after_success:
  - Rscript -e 'library(covr);codecov()'
r_packages:
  - PKI
warnings_are_errors: true
