language: r
cache: packages
warnings_are_errors: true

job_pointers:
  if_release: &if_release
    if: |
      repo = trestletech/plumber AND
      branch IN (master, rc-v0.5.0)
  if_plumber: &if_plumber
    if: |
      repo = trestletech/plumber
  if_always: &if_always
    if: |
      true

# Test on multiple dists with every flavor of R
jobs:
  include:
    - &trusty
      <<: *if_release
      name: Linux - trusty - oldrel
      os: linux
      dist: trusty
      r: oldrel
      addons:
        apt:
          sources:
            # PPA is only needed for (legacy) Trusty. Can be removed when Trusty is EOL.
            - sourceline: 'ppa:chris-lea/libsodium'
          packages:
            - libsodium-dev
    - <<: [*trusty, *if_always]
      name: Linux - trusty - release
      r: release
    - <<: *trusty
      name: Linux - trusty - devel
      r: devel

    - &xenial
      <<: *if_always
      name: Linux - xenial - oldrel
      os: linux
      dist: xenial
      r: oldrel
      addons:
        apt:
          packages:
            - libsodium-dev
    - <<: *xenial
      name: Linux - xenial - release; covr
      r: release
      r_packages:
        - covr
      after_success:
        # testing coverage
        - Rscript -e 'library(covr);codecov()'
    - <<: *xenial
      name: Linux - xenial - devel
      r: devel

    - &osx
      <<: *if_release
      name: macOS - oldrel
      os: osx
      brew_packages: libsodium
      r: oldrel
    - <<: [*osx, *if_always]
      name: macOS - release
      r: release
    - <<: *osx
      name: macOS - devel
      r: devel
