language: r
cache: packages
r_binary_packages:
  - testthat
  - XML
  - base64enc
  - rmarkdown
  - stringi
  - jsonlite
  - httpuv
r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'library(covr);codecov()'
r_packages:
  - PKI
warnings_are_errors: true
