language: r
sudo: required
r_binary_packages:
  - testthat
  - xml
  - base64enc
  - rmarkdown
  - stringi
  - rjson
  - httpuv
r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'library(covr);codecov()'
r_packages:
  - PKI
warnings_are_errors: true
