language: r
cache: packages
warnings_are_errors: true

# Test on multiple dists with every flavor of R
jobs:
  include:
    - &trusty
      name: Linux - trusty - oldrel
      os: linux
      dist: trusty
      r: oldrel
      if: |
        repo = trestletech/plumber AND
        branch IN (master, travis, rc-v0.5.0)
      addons:
        apt:
          sources:
            # PPA is only needed for (legacy) Trusty. Can be removed when Trusty is EOL.
            - sourceline: 'ppa:chris-lea/libsodium'
          packages:
            - libsodium-dev
    - <<: *trusty
      name: Linux - trusty - release
      r: release
      if: |
        true
    - <<: *trusty
      name: Linux - trusty - devel
      r: devel

    - &xenial
      name: Linux - xenial - oldrel
      os: linux
      dist: xenial
      r: oldrel
      addons:
        apt:
          packages:
            - libsodium-dev
    - <<: *xenial
      name: Linux - xenial - release; covr
      r: release
      r_packages:
        - covr
      after_success:
        # testing coverage
        - Rscript -e 'library(covr);codecov()'
    - <<: *xenial
      name: Linux - xenial - devel
      r: devel

    - &osx
      name: macOS - oldrel
      os: osx
      brew_packages: libsodium
      r: oldrel
      if: |
        repo = trestletech/plumber AND
        branch IN (master, travis, rc-v0.5.0)
    - <<: *osx
      name: macOS - release
      r: release
      if: |
        true
    - <<: *osx
      name: macOS - devel
      r: devel
